# Generated by Django 3.1.6 on 2021-03-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Ip address')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('machine_name', models.CharField(max_length=100, verbose_name='Computer name')),
                ('os', models.CharField(max_length=50, verbose_name='Operating system')),
            ],
        ),
    ]
