# Generated by Django 3.1.6 on 2021-03-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('ip_address', 'port')},
        ),
    ]
