global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        - rmmsystem:8000
        - 0.0.0.0:8000